extends Control
class_name Card

enum  CARD_CATEGORIES {MELEE, RANGED, DEFENSE, UTILITY}

var control_icon_textures : Array[Dictionary] = [
	{
		"atlas": load("res://art/ui/ui_mouse_icons.png"),
		"region" : Rect2(Vector2(0,0),Vector2(128,128)),
		"input" : "MOUSE1"
	},
	{
		"atlas":load("res://art/ui/ui_mouse_icons.png"),
		"region" : Rect2(Vector2(128,0),Vector2(128,128)),
		"input" : "MOUSE2"},
	{	
		"atlas":load("res://art/ui/ui_mouse_icons.png"),
		"region" : Rect2(Vector2(256,0),Vector2(128,128)),
		"input" : "MOUSE3"},
	{	
		"atlas":load("res://art/ui/ui_control_icons.png"),
		"region" : Rect2(Vector2(0,0),Vector2(128,128)),
		"input" : "Q"},
	{
		"atlas":load("res://art/ui/ui_control_icons.png"),
		"region" : Rect2(Vector2(128,0),Vector2(128,128)),
		"input" : "E"}
]


@export_category("General")
@export var card_type : CARD_CATEGORIES
@export var card_name : String = "Card Name"
@export var card_data : Dictionary = {"id":-1,"res":""} #Card Id for each distinct card. There can be copies
@export var control_icon : TextureRect
@export var cd_progress_bar : ProgressBar
@export var energy : int = 5 #How much "Ammo" does the card have?
var max_energy : int = 5

@export_category("Parameters")
@export var attack_damage : Dictionary = { #[min,max]
	"physical": [0,0],
	"fire": [0,0],
	"force": [0,0],
	"shock": [0,0],
	"cold": [0,0],
	"soul": [0,0]
}
@export var attack_resource : Resource #What is generated by the attack, bullet or melee?
@export var attack_velocity: float = 0.1
@export var rate: float = 0.5 #How fast can the card be activated / cooldown
@export var cooldownTimer : Timer
@export var hit_effects : Node #What effects can the card cause, trigger, etc.
@export var self_effects : Node

var card_hand_index : int  = -1
var player : Player #Belongs to this player
var ui : HUD #UI reference for performing actions
var card_ready : bool = true
var is_discarded: bool = false

signal was_discarded

func _ready() -> void:
	$CardTitle.text = card_name
	#print("Anchors " , anchor_left, anchor_top)
	cooldownTimer.wait_time = rate
	max_energy = energy
	update_energy_display()
	#Setup Progress Bar
	cd_progress_bar.max_value = rate

	
func _process(delta: float) -> void:
	if card_ready == false:
		cd_progress_bar.value -= delta

func update_energy_display():
	$EnergyLevel.text = str(energy)

#@rpc("any_peer", "call_local", "reliable")
func use_card():
	if energy > 0:
		cooldownTimer.start()
		energy = max(0,energy - 1)	
		card_ready = false
		cd_progress_bar.value = cd_progress_bar.max_value
		
		print(name, " Energy is now: ", energy)
	
		update_energy_display()
	
		#Run Card Action. This happens ONLY on the server
		if multiplayer.is_server():
			print("Run card action for card: ", name, " for client", multiplayer.get_unique_id())
			match card_type:
				CARD_CATEGORIES.MELEE:
					attack_action()
				CARD_CATEGORIES.RANGED:
					attack_action()
				CARD_CATEGORIES.DEFENSE:
					activate_effects()
				CARD_CATEGORIES.UTILITY:			
					activate_effects()

func activate_effects():
	if self_effects.get_child_count():
		for se : Effect in self_effects.get_children():
			var new_effect : Effect = load(se.scene_file_path).instantiate()
			player.player_add_effect(new_effect)

func get_attack_origin():
	match card_hand_index:
		0:
			return player.left_hand
		1:
			return player.right_hand
		2:
			return player.center_aim
		3:
			return player.left_hand
		4:
			return player.right_hand

func attack_action():
	#print("attack card ", attack_damage)
	var attack : Attack = attack_resource.instantiate()
	attack.attack_damage = attack_damage
	get_tree().current_scene.attacks_root.add_child(attack, true)	
	#POSITION
	var attack_origin = get_attack_origin()
	
	attack.position = attack_origin.global_position
	#Use to trigger setter for mp sync
	attack.spawn_on_load_trigger = true 
	
	var target_point : Vector3
	if player.gun_raycast.is_colliding():
		target_point = player.gun_raycast.get_collision_point()
	else:
		target_point = attack_origin.global_position + (-attack_origin.global_transform.basis.z * 1000)
	
	var direction = attack_origin.global_position.direction_to(target_point)
	attack.position += direction * attack.collision_shape.shape.radius
	#attack.look_at(direction,Vector3.UP)
	attack.apply_impulse(direction * attack_velocity)	
	attack.projectile_speed = attack_velocity
	attack.rotation = player.rotation
	
	
	if hit_effects.get_child_count():
		for he in hit_effects.get_children():
			var new_he = load(he.scene_file_path).instantiate()
			attack.add_child(new_he)


func drawn(index, set_ui, set_player):
	player = set_player
	ui = set_ui
	#print("Card Drawn/Moved, in hand index ", index)
	update_control_texture(index)

func update_control_texture(index):
	card_hand_index = index
	var new_texture = AtlasTexture.new()
	new_texture.atlas =  control_icon_textures[card_hand_index].atlas
	new_texture.region = control_icon_textures[card_hand_index].region
	control_icon.texture = new_texture
	control_icon.visible = true

func selected():
	$SelectedBorder.visible = true
	print("Card Selected: ", name, " ", position, " globalpos: ", global_position)
	
func deselected():
	$SelectedBorder.visible = false
	
func discarded(path,hud):
	var holder_node = Control.new()
	holder_node.name = "DiscardHolder"
	var follow_path = PathFollow2D.new()
	var refrect= ReferenceRect.new()
	holder_node.add_child(refrect,true)
	path.add_child(follow_path,true)
	hud.add_child(holder_node,true)
	holder_node.global_position = global_position
	holder_node.custom_minimum_size = self.custom_minimum_size
	holder_node.size = self.size
	holder_node.pivot_offset_ratio = Vector2(0.5,0.5)
	reparent(holder_node,true)

	#print("Rotation ", pivot_offset_ratio, " ", pivot_offset)
	#var progress_ratio = 0.0
	var travel_time = 3.0
	# Create and play the tween
	var discard_tween = create_tween()
	# Animate the progress_ratio from 0 to 1
	discard_tween.tween_property(follow_path, "progress_ratio", 1.0, travel_time).set_trans(Tween.TRANS_SINE).set_ease(Tween.EASE_IN_OUT)
	discard_tween.parallel().tween_method(
		func(_value): holder_node.global_position = follow_path.global_position - (holder_node.size/2),
		0.0, 1.0, travel_time
	)
	discard_tween.parallel().tween_property(self, "rotation_degrees", 720.0, travel_time)
	discard_tween.parallel().tween_property(self, "scale", Vector2(0.3,0.3), travel_time)
	discard_tween.finished.connect(add_to_discard_pile.bind(holder_node))

func add_to_discard_pile(holder_node : Control):	
	visible = false
	reparent(ui.discard_deck,false)	
	holder_node.queue_free()
	print(card_name, " added to discard pile")
	ui.discard_complete()
	was_discarded.emit()


func reset_card():
	is_discarded = false
	energy = max_energy
	card_ready = true
	update_energy_display()

func _on_cool_down_timeout() -> void:	
	if energy == 0 && is_discarded == false:		
		print("Card: ", name, " is out of energy,  server discard. CLient ID: ", multiplayer.get_unique_id())
		if multiplayer.is_server():
			CardManager.discard_card_from_hand(player.name.to_int(),card_hand_index)
			
	card_ready = true
